spring.application.name=parking

spring.datasource.url=jdbc:mysql://localhost:3306/proyecto_spring
spring.datasource.username=root
spring.datasource.password=ANDRESFG28.

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver