spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

logging.level.com.parkingspring.parking=WARN
logging.level.org.springframework.jdbc=WARN